#ifndef F_SH_LIMITS_GLS
#define F_SH_LIMITS_GLS

// Experimental
#define ENABLE_TANGENT_SPACE_NORMALS 0

// Note: These have to match pragma/game/game_limits.h!

// Must be dividable by 2!
#define MAX_SCENE_LIGHTS 192

#define MAX_SHADOW_MAPS 5
#define MAX_SHADOW_CUBE_MAPS 5
#define MAX_ACTIVE_SHADOW_SOURCES 20

#define MAX_CSM_CASCADES 4

#define MAX_BONES 1024

// Internal

#define MAX_SCENE_DIRECTIONAL_LIGHTS 4
#define MAX_SCENE_SPOT_LIGHTS ((MAX_SCENE_LIGHTS - MAX_SCENE_DIRECTIONAL_LIGHTS) / 2)
#define MAX_SCENE_POINT_LIGHTS ((MAX_SCENE_LIGHTS - MAX_SCENE_DIRECTIONAL_LIGHTS) / 2)

#define SCENE_SPOT_LIGHT_BUFFER_START 0
#define SCENE_SPOT_LIGHT_BUFFER_END (SCENE_SPOT_LIGHT_BUFFER_START + MAX_SCENE_SPOT_LIGHTS)

#define SCENE_POINT_LIGHT_BUFFER_START SCENE_SPOT_LIGHT_BUFFER_END
#define SCENE_POINT_LIGHT_BUFFER_END (SCENE_POINT_LIGHT_BUFFER_START + MAX_SCENE_POINT_LIGHTS)

#define SCENE_DIRECTIONAL_LIGHT_BUFFER_START SCENE_POINT_LIGHT_BUFFER_END
#define SCENE_DIRECTIONAL_LIGHT_BUFFER_END (SCENE_DIRECTIONAL_LIGHT_BUFFER_START + MAX_SCENE_DIRECTIONAL_LIGHTS)

#endif
