#ifndef F_SH_SCENE_FLAGS_GLS
#define F_SH_SCENE_FLAGS_GLS

#define SCENE_FLAG_BIT_NONE 0
#define SCENE_FLAG_BIT_USE_EXTENDED_VERTEX_WEIGHTS 1
#define SCENE_FLAG_BIT_RENDER_AS_3D_SKY (SCENE_FLAG_BIT_USE_EXTENDED_VERTEX_WEIGHTS << 1)
#define SCENE_FLAG_BIT_ALPHA_TEST (SCENE_FLAG_BIT_RENDER_AS_3D_SKY << 1)
#define SCENE_FLAG_BIT_LIGHTMAPS_ENABLED (SCENE_FLAG_BIT_ALPHA_TEST << 1)
#define SCENE_FLAG_BIT_NO_IBL (SCENE_FLAG_BIT_LIGHTMAPS_ENABLED << 1)
#define SCENE_FLAG_BIT_DISABLE_SHADOWS (SCENE_FLAG_BIT_NO_IBL << 1)
#define SCENE_FLAG_BIT_INDIRECT_LIGHTMAPS_ENABLED (SCENE_FLAG_BIT_DISABLE_SHADOWS << 1)
#define SCENE_FLAG_BIT_DIRECTIONAL_LIGHTMAPS_ENABLED (SCENE_FLAG_BIT_INDIRECT_LIGHTMAPS_ENABLED << 1)

struct SceneDrawInfo {
	vec4 clipPlane;
	vec4 drawOrigin; // w is scale
	vec2 depthBias;
	uint vertexAnimInfo;
	uint flags;
};

#endif
