#ifndef F_SH_VERTEX_DATA_LOCATIONS_GLS
#define F_SH_VERTEX_DATA_LOCATIONS_GLS

#ifndef SHADER_VERTEX_USER_DATA_LOCATION_COUNT
#define SHADER_VERTEX_USER_DATA_LOCATION_COUNT 0
#endif

#ifndef SHADER_VERTEX_DATA_LOCATION
#define SHADER_VERTEX_DATA_LOCATION 0
#endif
#ifndef SHADER_USER1_LOCATION
#define SHADER_USER1_LOCATION 17
#endif

// Note: Number of attributes must NOT exceed 32!

#endif
