#ifndef F_VS_BUFFER_LOCATIONS_GLS
#define F_VS_BUFFER_LOCATIONS_GLS

#ifndef SHADER_RENDER_BUFFER_INDEX_BUFFER_LOCATION
#define SHADER_RENDER_BUFFER_INDEX_BUFFER_LOCATION 0
#endif
#ifndef SHADER_BONE_WEIGHT_ID_LOCATION
#define SHADER_BONE_WEIGHT_ID_LOCATION (SHADER_RENDER_BUFFER_INDEX_BUFFER_LOCATION + 1)
#endif
#ifndef SHADER_BONE_WEIGHT_LOCATION
#define SHADER_BONE_WEIGHT_LOCATION (SHADER_BONE_WEIGHT_ID_LOCATION + 1)
#endif
#ifndef SHADER_BONE_WEIGHT_EXT_ID_LOCATION
#define SHADER_BONE_WEIGHT_EXT_ID_LOCATION (SHADER_BONE_WEIGHT_LOCATION + 1)
#endif
#ifndef SHADER_BONE_WEIGHT_EXT_LOCATION
#define SHADER_BONE_WEIGHT_EXT_LOCATION (SHADER_BONE_WEIGHT_EXT_ID_LOCATION + 1)
#endif

#ifndef SHADER_VERTEX_BUFFER_LOCATION // Can be overwritten by custom value, by defining it before this file is included
#define SHADER_VERTEX_BUFFER_LOCATION (SHADER_BONE_WEIGHT_EXT_LOCATION + 1)
#endif
#ifndef SHADER_UV_BUFFER_LOCATION
#define SHADER_UV_BUFFER_LOCATION (SHADER_VERTEX_BUFFER_LOCATION + 1)
#endif
#ifndef SHADER_NORMAL_BUFFER_LOCATION
#define SHADER_NORMAL_BUFFER_LOCATION (SHADER_UV_BUFFER_LOCATION + 1)
#endif
#ifndef SHADER_NORMAL_TANGENT_BUFFER_LOCATION
#define SHADER_NORMAL_TANGENT_BUFFER_LOCATION (SHADER_NORMAL_BUFFER_LOCATION + 1)
#endif
#ifndef SHADER_NORMAL_BITANGENT_BUFFER_LOCATION
#define SHADER_NORMAL_BITANGENT_BUFFER_LOCATION (SHADER_NORMAL_TANGENT_BUFFER_LOCATION + 1)
#endif
#ifndef SHADER_LIGHT_MAP_UV_BUFFER_LOCATION
#define SHADER_LIGHT_MAP_UV_BUFFER_LOCATION (SHADER_NORMAL_BITANGENT_BUFFER_LOCATION + 1)
#endif

#ifndef SHADER_USER_BUFFER1_LOCATION
#define SHADER_USER_BUFFER1_LOCATION (SHADER_LIGHT_MAP_UV_BUFFER_LOCATION + 1)
#endif
#ifndef SHADER_USER_BUFFER2_LOCATION
#define SHADER_USER_BUFFER2_LOCATION (SHADER_USER_BUFFER1_LOCATION + 1)
#endif
#ifndef SHADER_USER_BUFFER3_LOCATION
#define SHADER_USER_BUFFER3_LOCATION (SHADER_USER_BUFFER2_LOCATION + 1)
#endif
#ifndef SHADER_USER_BUFFER4_LOCATION
#define SHADER_USER_BUFFER4_LOCATION (SHADER_USER_BUFFER3_LOCATION + 1)
#endif
#ifndef SHADER_USER_BUFFER5_LOCATION
#define SHADER_USER_BUFFER5_LOCATION (SHADER_USER_BUFFER4_LOCATION + 1)
#endif
#ifndef SHADER_USER_BUFFER6_LOCATION
#define SHADER_USER_BUFFER6_LOCATION (SHADER_USER_BUFFER5_LOCATION + 1)
#endif
#ifndef SHADER_USER_BUFFER7_LOCATION
#define SHADER_USER_BUFFER7_LOCATION (SHADER_USER_BUFFER6_LOCATION + 1)
#endif
#ifndef SHADER_USER_BUFFER8_LOCATION
#define SHADER_USER_BUFFER8_LOCATION (SHADER_USER_BUFFER7_LOCATION + 1)
#endif

#endif
