name: Build lua-debug
description: 'Build lua-debug'
inputs:
  root_dir:
    description: 'Path to pragma directory.'
    default: 'pragma'
  deps_dir:
    description: 'Path to dependencies directory, where the build files for luamake and lua-debug will be stored.'
    default: 'deps'
  install_dir:
    description: 'Path to install directory, where the lua-debug files will be copied to.'
    default: 'install'
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "pragma > build_luadebug"
  
    - name: Install Prerequisites
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build binutils-dev libunwind-dev

    - name: Build luamake
      shell: bash
      run: |
        cd "${{inputs.root_dir}}/build_scripts"
        python "third_party/lua_debug/build_luamake.py" "${{inputs.deps_dir}}"

    - name: Build luadebug
      if: runner.os == 'Linux'
      shell: bash
      run: |
        cd "${{inputs.root_dir}}/build_scripts"
        python "third_party/lua_debug/build_luadebug.py" "${{inputs.deps_dir}}"

    # On Windows we have to run this in powershell
    - name: Build luadebug
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        cd "${{inputs.root_dir}}/build_scripts"
        python "third_party/lua_debug/build_luadebug.py" "${{inputs.deps_dir}}"

    - name: Install
      shell: bash
      run: |
        cd "${{inputs.root_dir}}/build_scripts"
        python "third_party/lua_debug/install_files.py" "${{inputs.deps_dir}}" "${{inputs.install_dir}}"
  
    - uses: Silverlan/common_actions/action_end@main
