name: Build Generic Module
description: 'Build Generic Module'
inputs:
  module:
    description: 'Module name'
    required: true
  build-config:
    description: 'The build configuration to use.'
    required: true
    default: "RelWithDebInfo"
outputs:
  build-dir:
    description: 'The directory where the build files are written to.'
    value: ${{ steps.set-output-vars.outputs.build-dir }}
  deps-dir:
    description: 'The directory where the dependencies are written to.'
    value: ${{ steps.set-output-vars.outputs.deps-dir }}
  install-dir:
    description: 'The directory where the installation files are written to.'
    value: ${{ steps.set-output-vars.outputs.install-dir }}
runs:
  using: "composite"
  steps:
    - name: Setup Pragma
      uses: Silverlan/pragma/github_actions/setup@master

    - name: "Download Module"
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        path: 'pragma/modules/${{ inputs.module }}'

    - name: Build Pragma
      id: build-pragma
      uses: Silverlan/pragma/github_actions/build@master
      with:
        build-args: '--with-common-modules=0 --with-essential-client-modules=0 --module ${{ inputs.module }}'

    - name: Set Output Variables
      shell: bash
      id: set-output-vars
      run: |
        echo "build-dir=${{ steps.build-pragma.outputs.build-dir }}" >> $GITHUB_OUTPUT
        echo "deps-dir=${{ steps.build-pragma.outputs.deps-dir }}" >> $GITHUB_OUTPUT
        echo "install-dir=${{ steps.build-pragma.outputs.install-dir }}" >> $GITHUB_OUTPUT
