name: Setup Pragma
description: 'Setup Pragma'
inputs:
  branch:
    description: 'The branch to clone Pragma from.'
    default: 'master'
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "pragma > setup"
  
    - name: Install Requirements
      uses: Silverlan/pragma/github_actions/install_requirements@master
      
    - name: Download Pragma
      shell: bash
      run: |
        git clone https://github.com/Silverlan/pragma.git --recurse-submodules --branch ${{ inputs.branch }}
  
    - uses: Silverlan/common_actions/action_end@main
