name: Install Requirements
description: 'Install Requirements'
inputs:
  with_cuda:
    description: 'Install CUDA?'
    required: true
    default: '0'
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "pragma > install_requirements"

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Install Dependencies
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt install ninja-build

    - name: Setup Visual Studio Developer Prompt
      if: ${{ runner.os == 'Windows' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    # This is a temporary fix until https://github.com/actions/runner-images/pull/9956 has been merged
    - name: Purge needrestart
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get purge needrestart

    - name: Set PIP_BREAK_SYSTEM_PACKAGES env variable
      shell: bash
      run: echo "PIP_BREAK_SYSTEM_PACKAGES=1" >> $GITHUB_ENV

    - name: Install numpy
      shell: bash
      id: install-numpy
      run: |
        pip install numpy
  
    - name: Print Disk Space
      shell: bash
      if: runner.os == 'Linux'
      run: |
        echo "Available disk space:"
        df -h

    #- name: Free Disk Space
    #  if: runner.os == 'Linux'
    #  uses: jlumbroso/free-disk-space@main
    #  with:
    #    tool-cache: false
    #    android: true
    #    dotnet: true
    #    haskell: true
    #    large-packages: true
    #    docker-images: true
    #    swap-storage: true

    #- name: Maximize build space
    #  if: ${{ runner.os == 'Linux' && !github.event.repository.private }}
    #  uses: easimon/maximize-build-space@master
    #  with:
    #    root-reserve-mb: 512
    #    swap-size-mb: 1024
    #    remove-dotnet: 'true'
        
    - name: Print Disk Space Post-Optimization
      shell: bash
      if: runner.os == 'Linux'
      run: |
        echo "Available disk space after optimization:"
        df -h

    - uses: Silverlan/common_actions/action_end@main
