name: Install Requirements
description: 'Install Requirements'
inputs:
  with_cuda:
    description: 'Install CUDA?'
    required: true
    default: '1'
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "pragma > install_requirements"

    # This is a temporary fix until https://github.com/actions/runner-images/pull/9956 has been merged
    - name: Purge needrestart
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get purge needrestart
  
    # Required for CUDA
    - name: Set up GCC 11
      shell: bash
      if: ${{ inputs.with_cuda == '1' && runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 60
        sudo update-alternatives --set gcc /usr/bin/gcc-11
        sudo update-alternatives --set g++ /usr/bin/g++-11

    # For Cycles
    - name: Install Cuda (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: Jimver/cuda-toolkit@v0.2.16
      if: ${{ inputs.with_cuda == '1' }}
      with:
        cuda: '12.2.0'
    # TODO: Install OptiX

    - name: Clone setup_cuda repository (Windows)
      if: ${{ runner.os != 'Linux' }}
      run: git clone https://github.com/Silverlan/setup_cuda.git

    - name: Install Cuda (Windows)
      if: ${{ runner.os != 'Linux' }}
      shell: pwsh
      run: setup_cuda/setup_cuda.ps1
      env:
          INPUT_CUDA_VERSION: "12.5.0"

    - name: Set PIP_BREAK_SYSTEM_PACKAGES env variable
      shell: bash
      run: echo "PIP_BREAK_SYSTEM_PACKAGES=1" >> $GITHUB_ENV

    - name: Install numpy
      shell: bash
      id: install-numpy
      run: |
        pip install numpy
  
    - name: Maximize build space
      if: runner.os == 'Linux'
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        
    - uses: Silverlan/common_actions/action_end@main
