#ifndef F_SH_PARTICLE_ALPHA_MODE_GLS
#define F_SH_PARTICLE_ALPHA_MODE_GLS

#define PT_ALPHA_MODE_ADDITIVE 0
#define PT_ALPHA_MODE_ADDITIVE_FULL 1
#define PT_ALPHA_MODE_OPAQUE 2
#define PT_ALPHA_MODE_MASKED 3
#define PT_ALPHA_MODE_TRANSLUCENT 4
#define PT_ALPHA_MODE_PREMULTIPLIED 5

#endif
