name: Run Tests
description: 'Run Tests'
inputs:
  install-dir:
    description: 'Installation Directory'
    required: true
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "pragma > run_tests"

    - name: Run Test Scripts
      shell: bash
      run: |
        cd "${{inputs.install-dir}}"
        ./pragma_server.exe -log 2 2 +map "test_physics" +"lua_exec tests/ci_runner_tests.lua"
        EXIT_CODE=$?
        # Check the exit code
        if [ $EXIT_CODE -eq 0 ]; then
          echo "Tests were successful."
        else
          echo "Tests have failed with exit code $EXIT_CODE."
          exit 1 # Exit the step with an error status
        fi

    - name: Check Result
      shell: bash
      run: |
        CI_CONTENTS=$(cat "${{inputs.install-dir}}/ci.txt")
        if [ "$CI_CONTENTS" == "0" ]; then
          echo "ci.txt contains '0'. Step failed."
          exit 1  # Exit the step with an error status
        fi

    - name: Upload Log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: log_server
        path: "${{inputs.install-dir}}/log_server.txt"
  
    - uses: Silverlan/common_actions/action_end@main
