#ifndef F_SH_COMPARE_OP_GLS
#define F_SH_COMPARE_OP_GLS

#define COMPARE_OP_NEVER 0
#define COMPARE_OP_LESS 1
#define COMPARE_OP_EQUAL 2
#define COMPARE_OP_LESS_OR_EQUAL 3
#define COMPARE_OP_GREATER 4
#define COMPARE_OP_NOT_EQUAL 5
#define COMPARE_OP_GREATER_OR_EQUAL 6
#define COMPARE_OP_ALWAYS 7

#endif
