#ifndef F_SH_PARTICLE_GENERIC_GLS
#define F_SH_PARTICLE_GENERIC_GLS

#ifndef LIGHTING_ENABLED
#define LIGHTING_ENABLED 1
#define LIGHTING_USE_INCIDENCE_ANGLE 0
#endif
#define USE_LIGHT_DIR_TS 0

#ifndef ENABLE_PARTICLE_TEXTURE
#define ENABLE_PARTICLE_TEXTURE 1
#endif

#define MATERIAL_NORMAL_MAP_ENABLED 0
#define USE_SPECULAR_MAP 0

#endif
