#ifndef F_SH_PARTICLE_RENDER_FLAGS_GLS
#define F_SH_PARTICLE_RENDER_FLAGS_GLS

#define PARTICLE_FRENDER_ANIMATED 1
#define PARTICLE_FRENDER_UNLIT (PARTICLE_FRENDER_ANIMATED << 1)
#define PARTICLE_FRENDER_SOFT (PARTICLE_FRENDER_UNLIT << 1)
#define PARTICLE_FRENDER_TEXTURE_SCROLLING (PARTICLE_FRENDER_SOFT << 1)
#define PARTICLE_FRENDER_ADDITIVE_BLEND_BY_COLOR (PARTICLE_FRENDER_TEXTURE_SCROLLING << 1)
#define PARTICLE_FRENDER_DEPTH_PASS (PARTICLE_FRENDER_ADDITIVE_BLEND_BY_COLOR << 1)

bool is_animated(uint flags) { return ((flags & PARTICLE_FRENDER_ANIMATED) != 0) ? true : false; }
bool is_particle_unlit(uint flags) { return ((flags & PARTICLE_FRENDER_UNLIT) != 0) ? true : false; }

#endif
