cmake_minimum_required(VERSION 4.1.2)

function(pr_get_normalized_identifier_name BASE_NAME)
    string(REPLACE "-" "_" IDENTIFIER_UNDERSCORE ${BASE_NAME})
    set(PRETTY_IDENTIFIER ${IDENTIFIER_UNDERSCORE})
    set(ARGV ${ARGN})
    list(LENGTH ARGV ARGC)
    if(ARGC GREATER 0)
        list(GET ARGV 0 PRETTY_IDENTIFIER)
    endif()
    string(TOUPPER ${IDENTIFIER_UNDERSCORE} NORMALIZED_IDENTIFIER)

    set(PRETTY_IDENTIFIER "${PRETTY_IDENTIFIER}" PARENT_SCOPE)
    set(NORMALIZED_IDENTIFIER "${NORMALIZED_IDENTIFIER}" PARENT_SCOPE)
    return()
endfunction()

include("${CMAKE_CURRENT_LIST_DIR}/pr_modules.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pr_dependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pr_sources.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pr_project.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pr_install.cmake")
