cmake_minimum_required(VERSION 3.28)

function(pr_get_normalized_identifier_name BASE_NAME)
    string(REPLACE "-" "_" IDENTIFIER_UNDERSCORE ${BASE_NAME})
    set(PRETTY_IDENTIFIER ${IDENTIFIER_UNDERSCORE})
    set(ARGV ${ARGN})
    list(LENGTH ARGV ARGC)
    if(ARGC GREATER 0)
        list(GET ARGV 0 PRETTY_IDENTIFIER)
    endif()
    string(TOUPPER ${IDENTIFIER_UNDERSCORE} NORMALIZED_IDENTIFIER)
    return(PROPAGATE PRETTY_IDENTIFIER NORMALIZED_IDENTIFIER)
endfunction()

include("${CMAKE_CURRENT_LIST_DIR}/pr_modules.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pr_dependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pr_sources.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/pr_project.cmake")
