#ifndef F_SH_PARTICLE_MODE_GLS
#define F_SH_PARTICLE_MODE_GLS

#define PARTICLE_ORIENTATION_TYPE_ALIGNED 0
#define PARTICLE_ORIENTATION_TYPE_UPRIGHT 1
#define PARTICLE_ORIENTATION_TYPE_STATIC 2
#define PARTICLE_ORIENTATION_TYPE_WORLD 3
#define PARTICLE_ORIENTATION_TYPE_BILLBOARD 4
#define PARTICLE_ORIENTATION_TYPE_VELOCITY 5

#endif
