name: Create Stable Module Release
on:
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build:
    name: Publish Release
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: 'ubuntu-24.04'
    steps:
      - name: Publish Release
        uses: Silverlan/pr_module_template/github_actions/publish_release@main
        with:
          version: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
